version: "3.8"

services:
  db:
    image: postgres:15
    container_name: backend-dev-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: nginx:alpine
    container_name: backend-dev-api
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://devuser:devpass@db:5432/devdb
      IMAGE_TAG: ${IMAGE_TAG:-latest}

volumes:
  db_data:
